name: primeiro workflow

on:
  push:
    branches:
      - main   
  schedule:
    - cron: "0 * * * *"  

jobs:
  executar_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3     

      - name: Configurar permissões para script
        run: chmod +x script.sh  

      - name: Executar script personalizado
        run: ./script.sh  

      - name: Exibir mensagem de conclusão
        run: echo "Execução concluída com sucesso!"

