name: primeiro workflow

on:
  push:
    branches:
      - main   

jobs:
  executar_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3     

      - name: Configurar permissões para script
        run: chmod +x meu_script.sh  

      - name: Executar script personalizado
        run: ./meu_script.sh  

      - name: Exibir mensagem de conclusão
        run: echo "Execução concluída com sucesso!"



